# Build the Jekyll site and publish to firebase hosting
#
# To set this up in Google Container Builder create a new build trigger based on branch. Set the following
# substitution variables:
#     _TOKEN      The Firebase auth token from `firebase login:ci` command.

steps:

- name: jekyll/builder:3.7
  id: 'fix-permissions'
  entrypoint: 'bin/chown'
  args: [ '-R', 'jekyll:jekyll', '/workspace' ]

- name: jekyll/builder:3.7
  id: 'build'
  args: [ 'jekyll', 'build' ]

- name: devillex/docker-firebase
  id: 'deploy'
  args: [ 'deploy', '--token', $_TOKEN ]

